In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[-3.0793e+10,  4.5751e-41, -2.5921e+29],
        [ 3.0637e-41,  4.4842e-44,  0.0000e+00],
        [ 4.4842e-44,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -3.0793e+10,  4.5751e-41],
        [ 2.5226e-18,  2.4283e-18,  4.6243e-44]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.4277, 0.2460, 0.1083],
        [0.4903, 0.2700, 0.7936],
        [0.6242, 0.6021, 0.8397],
        [0.1838, 0.5372, 0.5876],
        [0.9423, 0.9462, 0.0024]])


In [5]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

print(x.size())

# tuple
torch.Size([5,0])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.Size([5, 3])


torch.Size([5, 0])

In [6]:
y = x.view(15)
z = x.view(-1,5)
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [7]:
b = z.numpy()
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
print(z)
z.add_(1)
print(z)
print(b)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]], dtype=torch.float64)
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [9]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [12]:
x = torch.randn(1)
if torch.cuda.is_available():
    # cuda设备对象
    device = torch.device("cuda")
    # 直接在gpu上创建tensor
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([-2.0727], device='cuda:0')
tensor([-2.0727], dtype=torch.float64)
